title = "Introduction to modern LLMs textbook"

[[module.imports]]
path = "hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[[menu.main]]
name = "Docs"
pageRef = "/docs"
weight = 1

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 2

[[menu.main]]
name = "Contact ↗"
url = "https://github.com/qdosgit3"
weight = 3

[[menu.main]]
name = "Search"
weight = 4

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 5
url = "https://github.com/qdosgit3/llm_textbook"

  [menu.main.params]
  icon = "github"

[params.navbar]
displayTitle = true
displayLogo = false

[params.footer]
displayCopyright = true
displayPoweredBy = true

[params.editURL]
enable = true
base = "https://github.com/imfing/hextra-starter-template/edit/main/content"
